clear all
close all
clc
% code written in Matlab version R2021a Update 2 
% the objective is to solve 3 non-linear problems, two of convecion
% and one of conduction 
% unless otherwise sepicefied, all units are S.I.



Afuel=7775*1e-6;  % section occupied by fuel m^2
Aguaine=(2474+2239)*1e-6; %section occupied by cladding m^2
AAr=12146*1e-6; % section occupied by Argon m^2
Atot=25232*1e-6; % total cross section m^2
%inner and outer equiavlent radius of the FA
rout=89.78e-3;
rin=14.27e-3;
Lact=0.6;

Tai=378.5; %K
Afaext=0.338; % outer surface of the FA m^2
Afain=0.055832; % inner surface of the FA m^2
kb=5.67*1e-8; % Boltzmann constant
cpAr=520; %spectific heat of Argon
muout=3.77*1e-5; %dynamic viscosity of Argon at an estimated temperature in the outer section, between the case and the FA
muin=5.04*1e-5;% dynamic viscosity of Argon at an estimated temperature in the inner section,in the central channel of the FA
QQ=6470.6; % heat generated by a FA

%Thermal conductivity of the nuclear fuel
kfuel= @(T) (1/(0.014193+2.885*1e-4*T)+7.638*1e-11*T^3)*1/0.864;
%Thermal conductivity of the cladding
kguaine= @(T) 8.826+1.707*1e-2*T-2.351*1e-6*T^2;
%thermal conductivity of Argon 
kkAr=0.03;
kkArout=0.01772;

%Functions

%Raelygh number,where 0.6 il the characteristcal length
Raelygh= @(Tf, Tp, nu, alfa) 9.81*(1/Tf)*(Tp-Tai)*Lact^3/(nu*alfa);
%Density of Argon changing with temperature at a given pressure
rhoAr= @(T) 101300/(207.85*T);
%Prandtl number foncion
Prandtl= @(nu, alfa) nu/alfa;
%According to an Analytical calculation the requiremnts to apply this
%expression of the nusselt number are achieved in the region between the FA
%and the case, same can be said for the centeral channel(Nusseltin)
Nusseltout= @(Ra, Pr) 0.68+(0.670*Ra^(1/4))/(1+(0.492/Pr)^(9/16))^(4/9);
Nusseltin= @(Ra) 0.046*Ra^(1/3);

%Parameters for the cycle
err=10;
Tol=1e-4;
errCond=10;

%the assumption: physically the biggest part of the heat is being exchanged
%by radiation. sicne this problem require iterations to be solved, it
%starts considering all the heat as exhanged by radiation
Qconvin=0;
Qconvext=0;
Qirr(1)=QQ;
ii=1;

%this cycle will solve four non linear problems, depending one on the
%other with the set point iteration. In particular free convection inside
%and outside of the FA, conduction inside and radiation between the FA and
%the case

while err>Tol
    %a Temperature of the outer face of the FA is calculated
    Tfaext(ii)=(Qirr/(kb*Afaext)+Tai^4)^(1/4);
    %Tfilm is the temperature needed for the material properties, as far as
    %the formulas chosen require that temperature
    Tf=(Tfaext(ii)+Tai)/2;
    
    % determination of the material properties in the region between
    rhoout=rhoAr(Tf);
    alfa=kkArout/(cpAr*rhoout);
    nu=muout/rhoout;
    Pr=Prandtl(nu,alfa);
    Ra=Raelygh(Tf, Tfaext(ii),nu,alfa);
    hout=Nusseltout(Ra, Pr)*kkAr/Lact; %convection coefficient, aim of this calculation
    
    % setting the parameters for the conduction cycle
    Tmedia(1)=Tfaext(ii);
    errCond=10;
    
    %the assumption to begin the cycle is that the mean temperature inside
    %the FA is the temperature on the external surface
    while errCond>Tol
       % calculation of an equivalent conductivity, weighted on the areas
      kkeq=(kfuel(Tmedia(1))*Afuel+kguaine(Tmedia(1))*Aguaine ...
          +AAr*kkAr)/Atot;
      %solution of the conduction problem with flux imposed considering the
      %FA as a cylinder
       Tfain(ii)=QQ*log(rout/rin)/(2*pi*kkeq*Lact)+Tfaext(ii);
       
       %determination of a new mean temperature 
       Tmedia(2)=(Tfaext(ii)+Tfain(ii))/2;
       %errore calculation
       errCond=abs((Tmedia(1)-Tmedia(2))/Tmedia(1));
       
       %updating of the dipendent variable
       Tmedia(1)=Tmedia(2);
    end 
    %Tfilm for the circular channel
    Tfin=(Tfain(ii)+Tai)/2;
    %material properties in the circular channel
    rhoin=rhoAr(Tfin);
    alfain=kkAr/(cpAr*rhoin);
    nuin=muin/rhoin;
    Pr=Prandtl(nuin,alfain);
    Rain=Raelygh(Tfin, Tfain(ii),nuin,alfain);
    
    hin=Nusseltin(Rain)*kkAr/Lact; %  convection coefficient for the inner channel
    
    %determination of the heat exchanged by convection in the inner channel
    %and on the outer surface of the FA
    Qconvext=hout*Afaext*(Tfaext(ii)-Tai);
    Qconvin=hin*Afain*(Tfain(ii)-Tai);
    
    %updating the dependent variable to restart the cycle
    Qirr=QQ-Qconvext-Qconvin;
    
    %error determination
    if ii>1
       err=abs((Tfaext(ii-1)-Tfaext(ii))/Tfaext(ii-1)); 
    end
    %how many loops are made before convergance
    ii=ii+1;
end


% graphical part and profile temperature

%necessary data
VV=Atot*Lact;
qqq=6470.6/VV;

%computational grid
rr=linspace(rin, rout, 200)';
nn=length(rr);
dr=(rr(2)-rr(1));


%coefficient matrix with discrete differences
super=[0;1+dr./(2*rr(1:end-1))];
sub=[1-dr./(2*rr(2:end));0];
main=-2*ones(nn,1);

AA=spdiags([sub main super], -1:1, nn,nn);
bb=-(qqq*dr^2/kkeq)*ones(nn,1);

%boundary conditions
AA(1,1)=1;
AA(1,2)=0;
bb(1)=Tfaext(end);

AA(end,end)=1;
AA(end,end-1)=0;
bb(end)=Tfain(end);

%solution
TT=AA\bb;

%graph
figure(1)
title('Radial Temperature Distribution')
xlabel('FA radius [m] ')
ylabel('Temperature [K]')
grid on
hold on
xlim ([rin, rout])
set (gca, 'fontsize', 24)
plot(rr,TT,'r', 'linewidth', 3)



